run:
  timeout: 2m
linters:
  enable:
    - revive
issues:
  exclude-dirs:
    - go
    - opt
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA(4003|1019|5011):"
  include:
    - EXC0012
    - EXC0014
