name: check / frontend

on:
  push:
    branches: [main]
    paths:
      - '.github/workflow/pr-checks-frontend.yml'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/yarn.lock'
      - '**/package.json'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflow/pr-checks-frontend.yml'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/yarn.lock'
      - '**/package.json'

jobs:
  run-check:
    name: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: ["make vl-frontend-plugin-build", "yarn test"]
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install all dependencies
        run: yarn install

      - name: Run
        run: |
          ${{ matrix.scenario }}
