name: check / frontend

on:
  push:
    branches: [main]
    paths:
      - '.github/workflow/pr-checks-frontend.yml'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/yarn.lock'
      - '**/package.json'
      - '**/Makefile'
      - '**/Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflow/pr-checks-frontend.yml'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/yarn.lock'
      - '**/package.json'
      - '**/Makefile'
      - '**/Dockerfile'

jobs:
  run-check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.2

      - name: Install all dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
