name: release
on:
  push:
    tags:
      - 'v*'
env:
  PKG_TAG: ${{ github.ref_name }}
jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup golang caches
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/gocache-for-docker
          key: ${{ runner.os }}-golang-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Setup node caches
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Build plugin
        run: |
          yq -iP '.version="${{ env.PKG_TAG }}"' package.json -o json
          make vl-plugin-release
      - name: Upload release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.PKG_TAG }} ./dist/*
